#!/bin/bash
#
# SPDX-FileCopyrightText: 2023-2024 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

usage() {
    echo "Usage ${0} [-t topic] <remote> <merge_sha> <head> <branch>"
}

# Parse CLI args
while getopts "t:" opt; do
    case $opt in
        t)
            EXTRA+=",topic=${OPTARG}"
            ;;
        \?)
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

# Verify argument count
if [ "${#}" -ne 4 ]; then
    usage
    exit 1
fi

REMOTE="${1}"
MERGE_SHA="${2}"
HEAD="${3}"
BRANCH="${4}"
FIRST_SHA="$(git show -s --pretty=%P ${MERGE_SHA} | cut -d ' ' -f 1)"
SECOND_SHA="$(git show -s --pretty=%P ${MERGE_SHA} | cut -d ' ' -f 2)"

git push "${REMOTE}" "${HEAD}":refs/for/"${BRANCH}"%base="${FIRST_SHA}",base="${SECOND_SHA}${EXTRA}"
