#!/usr/bin/env bash

set -euo pipefail

[ -f carrier_list.pb ] || ./download_carrier_list.sh

for DEVICE in walleye taimen crosshatch bonito coral; do
  if [ "$DEVICE" = sunfish ]; then
    BUILD=RP1A.200720.011
  else
    BUILD=RP1A.200720.009
  fi

  if [ "$DEVICE" = walleye ]; then
    repo_dir="../device_google_muskie"
  else
    repo_dir="../device_google_${DEVICE}"
  fi
  [ -d "$repo_dir" ]

  DEVICE="$DEVICE" BUILD="$BUILD" ./download_factory_img.sh
  ./carriersettings_extractor.py CarrierSettings
  mv apns-full-conf.xml "${repo_dir}/apns-full-conf.xml"
  rm -r CarrierSettings
  rm vendor.xml

  (
    cd "$repo_dir"
    git checkout -b apns 2> /dev/null || git checkout apns
    git fetch origin
    git reset origin/11
    git add apns-full-conf.xml '*.mk'
    git commit -m "Include APNs from CarrierSettings

Generated by carriersettings-extractor from ${DEVICE}-${BUILD}"
  )
done
