# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: carrier_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63\x61rrier_list.proto\x12\x12\x63om.google.carrier\"^\n\tCarrierId\x12\x0f\n\x07mcc_mnc\x18\x01 \x01(\t\x12\r\n\x03spn\x18\x02 \x01(\tH\x00\x12\x0e\n\x04imsi\x18\x03 \x01(\tH\x00\x12\x0e\n\x04gid1\x18\x04 \x01(\tH\x00\x42\x0b\n\tmvno_dataJ\x04\x08\x05\x10\x06\"]\n\nCarrierMap\x12\x16\n\x0e\x63\x61nonical_name\x18\x01 \x01(\t\x12\x31\n\ncarrier_id\x18\x02 \x03(\x0b\x32\x1d.com.google.carrier.CarrierIdJ\x04\x08\x03\x10\x04\"M\n\x0b\x43\x61rrierList\x12-\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x1e.com.google.carrier.CarrierMap\x12\x0f\n\x07version\x18\x02 \x01(\x03')



_CARRIERID = DESCRIPTOR.message_types_by_name['CarrierId']
_CARRIERMAP = DESCRIPTOR.message_types_by_name['CarrierMap']
_CARRIERLIST = DESCRIPTOR.message_types_by_name['CarrierList']
CarrierId = _reflection.GeneratedProtocolMessageType('CarrierId', (_message.Message,), {
  'DESCRIPTOR' : _CARRIERID,
  '__module__' : 'carrier_list_pb2'
  # @@protoc_insertion_point(class_scope:com.google.carrier.CarrierId)
  })
_sym_db.RegisterMessage(CarrierId)

CarrierMap = _reflection.GeneratedProtocolMessageType('CarrierMap', (_message.Message,), {
  'DESCRIPTOR' : _CARRIERMAP,
  '__module__' : 'carrier_list_pb2'
  # @@protoc_insertion_point(class_scope:com.google.carrier.CarrierMap)
  })
_sym_db.RegisterMessage(CarrierMap)

CarrierList = _reflection.GeneratedProtocolMessageType('CarrierList', (_message.Message,), {
  'DESCRIPTOR' : _CARRIERLIST,
  '__module__' : 'carrier_list_pb2'
  # @@protoc_insertion_point(class_scope:com.google.carrier.CarrierList)
  })
_sym_db.RegisterMessage(CarrierList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARRIERID._serialized_start=42
  _CARRIERID._serialized_end=136
  _CARRIERMAP._serialized_start=138
  _CARRIERMAP._serialized_end=231
  _CARRIERLIST._serialized_start=233
  _CARRIERLIST._serialized_end=310
# @@protoc_insertion_point(module_scope)
